server.port: 8055


spring:
  application:
    name: jpo-atspm-spat-validation-service
  groovy:
    template:
      check-template-location: false
  thymeleaf:
    check-template-location: false
  jackson:
    serialization:
      write-dates-as-timestamps: false
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSZ
    time-zone: UTC

  data:
    # Mongo properties ref:
    # https://docs.spring.io/spring-boot/appendix/application-properties/index.html#application-properties.data.spring.mongodb.additional-hosts
    mongodb:
      database: ${CM_DATABASE_NAME:CV}
      host: ${DB_HOST_IP:localhost}
      port: ${MONGO_PORT:27017}
      username: ${MONGO_READ_WRITE_USER:ode}
      password: ${MONGO_READ_WRITE_PASS:replace_me}
      authentication-database: ${CM_MONGO_AUTH_DB:admin}
      # uri overrides individual properties above if it is set
      # https://docs.spring.io/spring-boot/appendix/application-properties/index.html#application-properties.data.spring.mongodb.uri
      #uri: ${CM_MONGO_URI:mongodb://ode:replace_me@localhost:27017/CV}

cm:
  batch:
    clock:
      # In normal operation, set offset to false for system time.
      # Or for testing or historical queries, set to true with start-timestamp set to the
      # time in the past to start querying from.
      offset: true
      start-timestamp: "2026-04-26T03:00:00Z"
    scheduler:
      thread.pool.size: 10
    atspm.spat.validation:
      algorithm: defaultAtspmSpatValidationAlgorithm
      client:
        base-url: ${CM_ATSPM_CLIENT_BASE_URL:http://localhost:8055}
        username: ${CM_ATSPM_CLIENT_USERNAME:username}
        password: ${CM_ATSPM_CLIENT_PASSWORD:password}
      local-time-zone: "America/Phoenix"
      interval: 10
      interval-units: MINUTES
      task-start-time-stagger: 1
      task-start-time-stagger-units: MINUTES
      # Offset time to run scheduled queries.
      # Set to an appropriate offset to ensure all data is present in the database for the
      # time period being queried.
      # It's not recommended to set this to 0, as current data in transit might be missed.
      grace-period-offset: 30
      grace-period-offset-units: MINUTES
      routes:
        - routeId: 6
          description: "Daisy Mountain Dr"
          signals:
            - signal-id: "1106121"
              intersection-id: 44383
              description: "Daisy Mountain Dr & Gavilan Peak Pkwy"
              enabled: true
              phases:
                - signal-group-id: 1
                  primary-phase: 1
                - signal-group-id: 2
                  primary-phase: 2
                - signal-group-id: 3
                  primary-phase: 3
                - signal-group-id: 4
                  primary-phase: 4
                - signal-group-id: 5
                  primary-phase: 5
                - signal-group-id: 6
                  primary-phase: 6
                - signal-group-id: 7
                  primary-phase: 7
                - signal-group-id: 8
                  primary-phase: 8
            - signal-id: "1106118"
              intersection-id: 0  # Missing MAP
              description: "Daisy Mountain Dr & Dedication Trail"
              enabled: false  # Missing SPATs
            - signal-id: "11061116"
              intersection-id: 54749
              description: "Daisy Mountain Dr & Meridian Dr"
              enabled: true
              phases:
                - signal-group-id: 1
                  primary-phase: 1
                - signal-group-id: 2
                  primary-phase: 2
                - signal-group-id: 3
                  primary-phase: 3
                - signal-group-id: 4
                  primary-phase: 4
                - signal-group-id: 5
                  primary-phase: 5
                - signal-group-id: 6
                  primary-phase: 6
                - signal-group-id: 7
                  primary-phase: 7
                - signal-group-id: 8
                  primary-phase: 8
            - signal-id: "11061114"
              intersection-id: 63397
              description: "Daisy Mountain Dr & Hastings Way"
              enabled: true
              phases:
                - signal-group-id: 1
                  primary-phase: 1
                - signal-group-id: 2
                  primary-phase: 2
                - signal-group-id: 3
                  primary-phase: 3
                - signal-group-id: 5
                  primary-phase: 5
                - signal-group-id: 6
                  primary-phase: 6
                - signal-group-id: 8
                  primary-phase: 8
            - signal-id: "1106112"
              intersection-id: 13710
              description: "Daisy Mountain Dr & Memorial Dr"
              enabled: false  # Missing ATSPM data
            - signal-id: "1106101"
              intersection-id: 22391
              description: "Anthem Way & Daisy Mountain Dr"
              enabled: true
              phases:
                - signal-group-id: 1
                  primary-phase: 1
                - signal-group-id: 2
                  primary-phase: 2
                - signal-group-id: 3
                  primary-phase: 3
                - signal-group-id: 4
                  primary-phase: 4
                - signal-group-id: 5
                  primary-phase: 5
                - signal-group-id: 6
                  primary-phase: 6
                - signal-group-id: 7
                  primary-phase: 7
                - signal-group-id: 8
                  primary-phase: 8
        - routeId: 9999
          description: "Fake route for testing scalability"
          signals:
            - signal-id: "1111111"
              intersection-id: 1111111
              description: "Fake signal 1"
              enabled: false
            - signal-id: "2222222"
              intersection-id: 2222222
              description: "Fake signal 2"
              enabled: false



