server.port: 8055


spring:
  application:
    name: jpo-atspm-spat-validation-service
  groovy:
    template:
      check-template-location: false
  thymeleaf:
    check-template-location: false
  data:
    # Mongo properties ref:
    # https://docs.spring.io/spring-boot/appendix/application-properties/index.html#application-properties.data.spring.mongodb.additional-hosts
    mongodb:
      database: ${CM_DATABASE_NAME:CV}
      host: ${DB_HOST_IP:localhost}
      port: ${MONGO_PORT:27017}
      username: ${MONGO_READ_WRITE_USER:ode}
      password: ${MONGO_READ_WRITE_PASS:replace_me}
      authentication-database: ${CM_MONGO_AUTH_DB:admin}
      # uri overrides individual properties above if it is set
      # https://docs.spring.io/spring-boot/appendix/application-properties/index.html#application-properties.data.spring.mongodb.uri
      #uri: ${CM_MONGO_URI:mongodb://ode:replace_me@localhost:27017/CV}

cm:
  batch:
    scheduler:
      thread.pool.size: 10
    atspm.spat.validation:
      algorithm: defaultAtspmSpatValidationAlgorithm
      client:
        base-url: ${CM_ATSPM_CLIENT_BASE_URL:http://localhost:8055}
        username: ${CM_ATSPM_CLIENT_USERNAME:username}
        password: ${CM_ATSPM_CLIENT_PASSWORD:password}
      local-time-zone: "America/Phoenix"
      interval: 10
      interval-units: MINUTES
      task-start-time-stagger: 1
      task-start-time-stagger-units: MINUTES
      grace-period-offset: 2
      grace-period-offset-units: HOURS
      routes:
        - routeId: 6
          description: "Daisy Mountain Dr"
          signals:
            - signalId: "1106121"
              description: "Daisy Mountain Dr & Gavilan Peak Pkwy"
              enabled: true
            - signalId: "1106118"
              description: "Daisy Mountain Dr & Dedication Trail"
              enabled: true
            - signalId: "11061116"
              description: "Daisy Mountain Dr & Meridian Dr"
              enabled: true
            - signalId: "11061114"
              description: "Daisy Mountain Dr & Hastings Way"
              enabled: true
            - signalId: "1106112"
              description: "Daisy Mountain Dr & Memorial Dr"
              enabled: false
            - signalId: "1106101"
              description: "Anthem Way & Daisy Mountain Dr"
              enabled: true
        - routeId: 9999
          description: "Fake route for testing scalability"
          signals:
            - signalId: "1111111"
              description: "Fake signal 1"
              enabled: false
            - signalId: "2222222"
              description: "Fake signal 2"
              enabled: false


